# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resume',
            new_name='ResumePage',
        ),
    ]
