# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpage_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='main_image',
        ),
    ]
