# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_embed_videos', '0001_initial'),
        ('blog', '0019_auto_20170730_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='page_content',
            field=wagtail.wagtailcore.fields.StreamField([('h2_heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('blockquote', wagtail.wagtailcore.blocks.BlockQuoteBlock()), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock()), ('link', wagtail.wagtailcore.blocks.URLBlock()), ('codeblock', wagtail.wagtailcore.blocks.StructBlock([(b'language', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'python', b'Python'), (b'bash', b'Bash/Shell'), (b'html', b'HTML'), (b'css', b'CSS'), (b'scss', b'SCSS'), (b'json', b'JSON'), (b'c', b'C'), (b'java', b'Java'), (b'arduino', b'Arduino')])), (b'style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'syntax', b'default'), (b'emacs', b'emacs'), (b'monokai', b'monokai'), (b'vim', b'vim'), (b'xcode', b'xcode')])), (b'code', wagtail.wagtailcore.blocks.TextBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_embed_videos.EmbedVideo', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
