# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_embed_videos', '0001_initial'),
        ('blog', '0020_auto_20170730_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBasedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_embed_videos.EmbedVideo', verbose_name='Video')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='media',
        ),
    ]
