# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20170730_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videobasedmodel',
            name='video',
        ),
        migrations.DeleteModel(
            name='VideoBasedModel',
        ),
    ]
