# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:51
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20170730_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='code_block',
            field=wagtail.wagtailcore.fields.StreamField([('code_block', wagtail.wagtailcore.blocks.StructBlock([(b'language', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'python', b'Python'), (b'bash', b'Bash/Shell'), (b'html', b'HTML'), (b'css', b'CSS'), (b'scss', b'SCSS')])), (b'code', wagtail.wagtailcore.blocks.TextBlock())]))], default=''),
            preserve_default=False,
        ),
    ]
