# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogindexrelatedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
