# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('portfolio', '0002_portfoliocategory_portfolioindexpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioItemPage',
            new_name='PortfolioPage',
        ),
        migrations.DeleteModel(
            name='PortfolioCategory',
        ),
        migrations.RemoveField(
            model_name='portfolioindexpage',
            name='page_ptr',
        ),
        migrations.RenameField(
            model_name='portfoliopage',
            old_name='body',
            new_name='intro',
        ),
        migrations.DeleteModel(
            name='PortfolioIndexPage',
        ),
    ]
