# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('portfolio', '0003_auto_20170721_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliopage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='PortfolioPage',
        ),
    ]
